version: '2'
services:
  agent1:
    build: .
    environment:
      - BROKER_ADDRESS=tcp://broker:1883
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  agent2:
    build: .
    environment:
      - BROKER_ADDRESS=tcp://broker:1883
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  test-client-connector:
    container_name: test-client-connector
    build: https://github.com/SENERGY-Platform/test-client-connector.git
    image: test-client-connector
    volumes:
      - './cc-lib:/usr/src/app/cc-lib'